FROM python:3.9-slim
WORKDIR /app
COPY cloud/requirements.txt .
RUN pip install -r requirements.txt
RUN apt-get update && apt-get install -y netcat-openbsd
COPY cloud/cloud.py .
COPY common/ common/
COPY data/ /data
CMD ["python", "cloud.py"]