version: '3.8'

services:
  cloud:
    build:
      context: .
      dockerfile: cloud/Dockerfile
    ports:
      - "6000:6000"
    volumes:
      - ./data:/data
    networks:
      - hfl-net
    deploy:
      resources:
        limits:
          cpus: '0.5'
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "6000"]
      interval: 5s
      timeout: 5s
      retries: 10

  edge0:
    build:
      context: .
      dockerfile: edge/Dockerfile
    command: ["python", "edge.py", "0"]
    ports:
      - "5000:5000"
    depends_on:
      cloud:
        condition: service_healthy
    networks:
      - hfl-net
    deploy:
      resources:
        limits:
          cpus: '0.3'
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "5000"]
      interval: 5s
      timeout: 5s
      retries: 10

  edge1:
    build:
      context: .
      dockerfile: edge/Dockerfile
    command: ["python", "edge.py", "1"]
    ports:
      - "5001:5001"
    depends_on:
      cloud:
        condition: service_healthy
    networks:
      - hfl-net
    deploy:
      resources:
        limits:
          cpus: '0.3'
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "5001"]
      interval: 5s
      timeout: 5s
      retries: 10

  edge2:
    build:
      context: .
      dockerfile: edge/Dockerfile
    command: ["python", "edge.py", "2"]
    ports:
      - "5002:5002"
    depends_on:
      cloud:
        condition: service_healthy
    networks:
      - hfl-net
    deploy:
      resources:
        limits:
          cpus: '0.3'
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "5002"]
      interval: 5s
      timeout: 5s
      retries: 10

  edge3:
    build:
      context: .
      dockerfile: edge/Dockerfile
    command: ["python", "edge.py", "3"]
    ports:
      - "5003:5003"
    depends_on:
      cloud:
        condition: service_healthy
    networks:
      - hfl-net
    deploy:
      resources:
        limits:
          cpus: '0.3'
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "5003"]
      interval: 5s
      timeout: 5s
      retries: 10

  client0:
    build:
      context: .
      dockerfile: client/Dockerfile
    command: ["python", "client.py", "0", "0.25", "5"]
    depends_on:
      edge0:
        condition: service_healthy
    networks:
      - hfl-net
    deploy:
      resources:
        limits:
          cpus: '0.1'

  client1:
    build:
      context: .
      dockerfile: client/Dockerfile
    command: ["python", "client.py", "1", "0.25", "5"]
    depends_on:
      edge0:
        condition: service_healthy
    networks:
      - hfl-net
    deploy:
      resources:
        limits:
          cpus: '0.15'

  client2:
    build:
      context: .
      dockerfile: client/Dockerfile
    command: ["python", "client.py", "2", "0.25", "5"]
    depends_on:
      edge0:
        condition: service_healthy
    networks:
      - hfl-net
    deploy:
      resources:
        limits:
          cpus: '0.1'

  client3:
    build:
      context: .
      dockerfile: client/Dockerfile
    command: ["python", "client.py", "3", "0.25", "5"]
    depends_on:
      edge1:
        condition: service_healthy
    networks:
      - hfl-net
    deploy:
      resources:
        limits:
          cpus: '0.15'

  client4:
    build:
      context: .
      dockerfile: client/Dockerfile
    command: ["python", "client.py", "4", "0.25", "5"]
    depends_on:
      edge1:
        condition: service_healthy
    networks:
      - hfl-net
    deploy:
      resources:
        limits:
          cpus: '0.1'

  client5:
    build:
      context: .
      dockerfile: client/Dockerfile
    command: ["python", "client.py", "5", "0.25", "5"]
    depends_on:
      edge2:
        condition: service_healthy
    networks:
      - hfl-net
    deploy:
      resources:
        limits:
          cpus: '0.15'

  client6:
    build:
      context: .
      dockerfile: client/Dockerfile
    command: ["python", "client.py", "6", "0.25", "5"]
    depends_on:
      edge2:
        condition: service_healthy
    networks:
      - hfl-net
    deploy:
      resources:
        limits:
          cpus: '0.1'

  client7:
    build:
      context: .
      dockerfile: client/Dockerfile
    command: ["python", "client.py", "7", "0.25", "5"]
    depends_on:
      edge3:
        condition: service_healthy
    networks:
      - hfl-net
    deploy:
      resources:
        limits:
          cpus: '0.15'

  client8:
    build:
      context: .
      dockerfile: client/Dockerfile
    command: ["python", "client.py", "8", "0.25", "5"]
    depends_on:
      edge3:
        condition: service_healthy
    networks:
      - hfl-net
    deploy:
      resources:
        limits:
          cpus: '0.1'

  client9:
    build:
      context: .
      dockerfile: client/Dockerfile
    command: ["python", "client.py", "9", "0.25", "5"]
    depends_on:
      edge3:
        condition: service_healthy
    networks:
      - hfl-net
    deploy:
      resources:
        limits:
          cpus: '0.15'

networks:
  hfl-net:
    driver: bridge