services:
  cloud:
    build:
      context: .
      dockerfile: cloud/Dockerfile
    hostname: cloud-1
    ports:
      - "6000:6000"
    volumes:
      - ./mnist_data:/app/data/MNIST/raw
    networks:
      - hfl-net
    tty: true  # Keep container alive for inspection
    command: ["python", "cloud.py"]  # Explicit command for clarity

  edge0:
    build:
      context: .
      dockerfile: edge/Dockerfile
    hostname: edge0-1
    command: ["python", "edge.py", "0", "3"]
    ports:
      - "5000:5000"
    depends_on:
      - cloud
    volumes:
      - ./mnist_data:/app/data/MNIST/raw
    networks:
      - hfl-net

  edge1:
    build:
      context: .
      dockerfile: edge/Dockerfile
    hostname: edge1-1
    command: ["python", "edge.py", "1", "3"]
    ports:
      - "5001:5001"
    depends_on:
      - cloud
    volumes:
      - ./mnist_data:/app/data/MNIST/raw
    networks:
      - hfl-net

  edge2:
    build:
      context: .
      dockerfile: edge/Dockerfile
    hostname: edge2-1
    command: ["python", "edge.py", "2", "2"]
    ports:
      - "5002:5002"
    depends_on:
      - cloud
    volumes:
      - ./mnist_data:/app/data/MNIST/raw
    networks:
      - hfl-net

  edge3:
    build:
      context: .
      dockerfile: edge/Dockerfile
    hostname: edge3-1
    command: ["python", "edge.py", "3", "2"]
    ports:
      - "5003:5003"
    depends_on:
      - cloud
    volumes:
      - ./mnist_data:/app/data/MNIST/raw
    networks:
      - hfl-net

  client0:
    build:
      context: .
      dockerfile: client/Dockerfile
    command: ["python", "client.py", "0", "0.25"]
    depends_on:
      - edge0
    volumes:
      - ./mnist_data:/app/data/MNIST/raw
    networks:
      - hfl-net

  client1:
    build:
      context: .
      dockerfile: client/Dockerfile
    command: ["python", "client.py", "1", "0.25"]
    depends_on:
      - edge0
    volumes:
      - ./mnist_data:/app/data/MNIST/raw
    networks:
      - hfl-net

  client2:
    build:
      context: .
      dockerfile: client/Dockerfile
    command: ["python", "client.py", "2", "0.25"]
    depends_on:
      - edge0
    volumes:
      - ./mnist_data:/app/data/MNIST/raw
    networks:
      - hfl-net

  client3:
    build:
      context: .
      dockerfile: client/Dockerfile
    command: ["python", "client.py", "3", "0.25"]
    depends_on:
      - edge1
    volumes:
      - ./mnist_data:/app/data/MNIST/raw
    networks:
      - hfl-net

  client4:
    build:
      context: .
      dockerfile: client/Dockerfile
    command: ["python", "client.py", "4", "0.25"]
    depends_on:
      - edge1
    volumes:
      - ./mnist_data:/app/data/MNIST/raw
    networks:
      - hfl-net

  client5:
    build:
      context: .
      dockerfile: client/Dockerfile
    command: ["python", "client.py", "5", "0.25"]
    depends_on:
      - edge1
    volumes:
      - ./mnist_data:/app/data/MNIST/raw
    networks:
      - hfl-net

  client6:
    build:
      context: .
      dockerfile: client/Dockerfile
    command: ["python", "client.py", "6", "0.25"]
    depends_on:
      - edge2
    volumes:
      - ./mnist_data:/app/data/MNIST/raw
    networks:
      - hfl-net

  client7:
    build:
      context: .
      dockerfile: client/Dockerfile
    command: ["python", "client.py", "7", "0.25"]
    depends_on:
      - edge2
    volumes:
      - ./mnist_data:/app/data/MNIST/raw
    networks:
      - hfl-net

  client8:
    build:
      context: .
      dockerfile: client/Dockerfile
    command: ["python", "client.py", "8", "0.25"]
    depends_on:
      - edge3
    volumes:
      - ./mnist_data:/app/data/MNIST/raw
    networks:
      - hfl-net

  client9:
    build:
      context: .
      dockerfile: client/Dockerfile
    command: ["python", "client.py", "9", "0.25"]
    depends_on:
      - edge3
    volumes:
      - ./mnist_data:/app/data/MNIST/raw
    networks:
      - hfl-net

networks:
  hfl-net:
    driver: bridge