FROM python:3.9-slim
WORKDIR /app
COPY edge/requirements.txt .
RUN pip install -r requirements.txt
RUN apt-get update && apt-get install -y netcat-openbsd
COPY edge/edge.py .
COPY common/ common/
CMD ["python", "edge.py"]